

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ProdavnicaLaptopova.Models.EFRepository
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class ProdavnicaLaptopovaEntities : DbContext
{
    public ProdavnicaLaptopovaEntities()
        : base("name=ProdavnicaLaptopovaEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Laptop> Laptop { get; set; }

    public virtual DbSet<Magacin> Magacin { get; set; }

    public virtual DbSet<Racun> Racun { get; set; }

    public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }

    public virtual DbSet<UnosUMagacin> UnosUMagacin { get; set; }

    public virtual DbSet<Role> Role { get; set; }

    public virtual DbSet<User> User { get; set; }

    public virtual DbSet<UserRole> UserRole { get; set; }

}

}

