//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdavnicaLaptopova.Models.EFRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Racun
    {
        public int RacunID { get; set; }
        public double Iznos { get; set; }
        public Nullable<int> Storniran { get; set; }
        public int LaptopID { get; set; }
    
        public virtual Laptop Laptop { get; set; }
    }
}
