
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ProdavnicaLaptopova.Models.EFRepository
{

using System;
    using System.Collections.Generic;
    
public partial class UnosUMagacin
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public UnosUMagacin()
    {

        this.Magacin = new HashSet<Magacin>();

    }


    public int UnosUMagacinID { get; set; }

    public int BarKod { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Magacin> Magacin { get; set; }

}

}
